language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t vyamnur/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vyamnur/docker-react npm run test